project_id = "ufyvllgimtkyehfkfxoi"

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.configure-client-webhook]
verify_jwt = false

[functions.fastsoft-webhook]
verify_jwt = false

[functions.expire-pending-orders]
verify_jwt = false

[functions.cart-recovery]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.send-telegram-message]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.test-tiktok-event]
verify_jwt = false

[functions.test-facebook-event]
verify_jwt = false

[functions.create-tiktok-link]
verify_jwt = false

[functions.process-daily-fees]
verify_jwt = false

[functions.add-balance]
verify_jwt = false

[functions.check-delinquents]
verify_jwt = false

[functions.admin-balance]
verify_jwt = false
 
 [functions.asaas-balance-webhook]
 verify_jwt = false
